// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfyiqedyesexxflbmhou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmeWlxZWR5ZXNleHhmbGJtaG91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4ODU4NzEsImV4cCI6MjA1NjQ2MTg3MX0.G9NCmOMnB_K97AXxNYWI7dbJReTi6qh84elhHBnyFqQ";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Job-related API functions
export const fetchJobs = async () => {
  const { data, error } = await supabase
    .from('jobs')
    .select('*')
    .eq('is_active', true)
    .order('created_at', { ascending: false });
  
  if (error) throw error;
  return data;
};

export const fetchJobById = async (id: string) => {
  const { data, error } = await supabase
    .from('jobs')
    .select('*')
    .eq('id', id)
    .single();
  
  if (error) throw error;
  return data;
};

export const applyForJob = async (jobId: string, note?: string) => {
  const { data: user } = await supabase.auth.getUser();
  
  if (!user.user) {
    throw new Error('You must be logged in to apply for jobs');
  }
  
  const { data, error } = await supabase
    .from('job_applications')
    .insert([
      { job_id: jobId, applicant_id: user.user.id, note }
    ])
    .select()
    .single();
  
  if (error) {
    if (error.code === '23505') { // Unique violation
      throw new Error('You have already applied for this job');
    }
    throw error;
  }
  
  return data;
};

export const checkJobApplication = async (jobId: string) => {
  const { data: user } = await supabase.auth.getUser();
  
  if (!user.user) return null;
  
  const { data, error } = await supabase
    .from('job_applications')
    .select('*')
    .eq('job_id', jobId)
    .eq('applicant_id', user.user.id)
    .maybeSingle();
  
  if (error) throw error;
  return data;
};

export const fetchUserApplications = async () => {
  const { data: user } = await supabase.auth.getUser();
  
  if (!user.user) {
    throw new Error('You must be logged in to view your applications');
  }
  
  const { data, error } = await supabase
    .from('job_applications')
    .select(`
      *,
      jobs:job_id (*)
    `)
    .eq('applicant_id', user.user.id)
    .order('created_at', { ascending: false });
  
  if (error) throw error;
  return data;
};

// User profile and document verification functions
export const updateUserProfile = async (profileData: any) => {
  const { data: user } = await supabase.auth.getUser();
  
  if (!user.user) {
    throw new Error('You must be logged in to update your profile');
  }
  
  const { data, error } = await supabase
    .from('profiles')
    .update(profileData)
    .eq('id', user.user.id)
    .select();
  
  if (error) throw error;
  return data;
};

export const getUserProfile = async () => {
  const { data: user } = await supabase.auth.getUser();
  
  if (!user.user) {
    throw new Error('You must be logged in to view your profile');
  }
  
  const { data, error } = await supabase
    .from('profiles')
    .select('*')
    .eq('id', user.user.id)
    .single();
  
  if (error) throw error;
  return data;
};

export const submitDocumentVerification = async (documents: { 
  prc_license?: string, 
  tin_number?: string, 
  government_id?: string 
}) => {
  const { data: user } = await supabase.auth.getUser();
  
  if (!user.user) {
    throw new Error('You must be logged in to submit documents');
  }
  
  const updateData = {
    ...documents,
    document_verification_status: 'submitted'
  };
  
  const { data, error } = await supabase
    .from('profiles')
    .update(updateData)
    .eq('id', user.user.id)
    .select();
  
  if (error) throw error;
  return data;
};

// Hospital job management functions
export const fetchHospitalJobs = async () => {
  const { data: user } = await supabase.auth.getUser();
  
  if (!user.user) {
    throw new Error('You must be logged in to view your job postings');
  }
  
  const { data, error } = await supabase
    .from('jobs')
    .select('*')
    .eq('created_by', user.user.id)
    .order('created_at', { ascending: false });
  
  if (error) throw error;
  return data;
};

export const createJobPosting = async (jobData: any) => {
  const { data: user } = await supabase.auth.getUser();
  
  if (!user.user) {
    throw new Error('You must be logged in to create job postings');
  }
  
  const { data, error } = await supabase
    .from('jobs')
    .insert([{ ...jobData, created_by: user.user.id }])
    .select();
  
  if (error) throw error;
  return data;
};

export const updateJobPosting = async (jobId: string, jobData: any) => {
  const { data: user } = await supabase.auth.getUser();
  
  if (!user.user) {
    throw new Error('You must be logged in to update job postings');
  }
  
  const { data, error } = await supabase
    .from('jobs')
    .update(jobData)
    .eq('id', jobId)
    .eq('created_by', user.user.id) // Ensure job belongs to this user
    .select();
  
  if (error) throw error;
  return data;
};

export const deleteJobPosting = async (jobId: string) => {
  const { data: user } = await supabase.auth.getUser();
  
  if (!user.user) {
    throw new Error('You must be logged in to delete job postings');
  }
  
  const { error } = await supabase
    .from('jobs')
    .delete()
    .eq('id', jobId)
    .eq('created_by', user.user.id); // Ensure job belongs to this user
  
  if (error) throw error;
  return { success: true };
};

export const fetchJobApplications = async (jobId: string) => {
  const { data: user } = await supabase.auth.getUser();
  
  if (!user.user) {
    throw new Error('You must be logged in to view applications');
  }
  
  // First check if the job belongs to the user
  const { data: jobData, error: jobError } = await supabase
    .from('jobs')
    .select('id')
    .eq('id', jobId)
    .eq('created_by', user.user.id)
    .single();
  
  if (jobError || !jobData) {
    throw new Error('Job not found or you do not have permission to view its applications');
  }
  
  const { data, error } = await supabase
    .from('job_applications')
    .select(`
      *,
      profiles:applicant_id (id, first_name, last_name, avatar_url, title, contact_email)
    `)
    .eq('job_id', jobId)
    .order('created_at', { ascending: false });
  
  if (error) throw error;
  return data;
};

export const updateApplicationStatus = async (applicationId: string, status: string) => {
  const { data: user } = await supabase.auth.getUser();
  
  if (!user.user) {
    throw new Error('You must be logged in to update application status');
  }
  
  // First get the application to check if the job belongs to the user
  const { data: applicationData, error: appError } = await supabase
    .from('job_applications')
    .select(`
      job_id,
      jobs:job_id (created_by)
    `)
    .eq('id', applicationId)
    .single();
  
  if (appError || !applicationData) {
    throw new Error('Application not found');
  }
  
  // Check if the job belongs to the user
  if (applicationData.jobs.created_by !== user.user.id) {
    throw new Error('You do not have permission to update this application');
  }
  
  const { data, error } = await supabase
    .from('job_applications')
    .update({ status })
    .eq('id', applicationId)
    .select();
  
  if (error) throw error;
  return data;
};
